#!/bin/sh

# config
EXECUTABLE=/usr/local/bin/p44sbbd
RS485PORT=/dev/ttyUSB0
JSONAPIPORT=9999
STATEDIR=/var/lib/p44sbbd
LOGLEVEL=5

# make the state dir
mkdir -p ${STATEDIR}
chmod 777 ${STATEDIR}

# run the daemon
exec ${EXECUTABLE} \
  --rs485connection ${RS485PORT} \
  --jsonapiport ${JSONAPIPORT} \
  --statedir ${STATEDIR} \
  -l ${LOGLEVEL} \
  </dev/null
